### ISSUE TITLE
Give page > Destination > Editing Cards

### ISSUE THREAD

**Issue by gracesooyeun** [indeedandtruth/website#15]
1. Suzy is willing to put down 'St. Michel's' from the Destinations > Missionaries. 
2. Suzy wants to know when people successfully donate, are they get redirected to the maillist joining page.
![Uploading Screenshot 2024-11-22 at 9.59.16 PM.png…]()

**Comment by tyler-paulson** [comment]
@gracesooyeun You should have access to Donately to unpublish campaigns. Let me know if not. It takes an hour for changes on Donately to sync over to the site.

I have the Donately / MailChimp integration on my todo list and I'm pushing to have it done by Giving Tuesday.

**Comment by gracesooyeun** [comment]
<img width="547" alt="Screenshot 2024-11-22 at 10 02 36 PM" src="https://github.com/user-attachments/assets/29b041e8-dfb5-4c84-a223-9d113e4f93f5">

I think I did it!! Thank you so much Tyler :D
